server:
  servlet:
    context-path: /account
spring:
  application:
    name: account
  datasource:
    name: orderingsystem
    url: jdbc:mysql://sirius-database.mysql.database.azure.com:3306/orderingsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=true&requireSSL=false
    username: sirius@sirius-database
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.sirius.entity
  mapper-locations: classpath:/mapping/*.xml
  
application:
  message: it's good.
