server:
  port: 8040
spring:
  application:
    name: order
  datasource:
    name: orderingsystem
    url: jdbc:mysql://sirius-database.mysql.database.azure.com:3306/orderingsystem?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=true&requireSSL=false
    username: sirius@sirius-database
    password: Database123456
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.sirius.entity
  mapper-locations: classpath:/mapping/*.xml